name = "disgit"
main = "src/index.ts"
compatibility_date = "2022-11-10"
usage_model = "bundled"

workers_dev = true

[vars]
IGNORED_BRANCH_REGEX="^gh-readonly-queue/.*"
IGNORED_BRANCHES=""
IGNORED_USERS="github-actions[bot],renovate[bot]"

# Uses secrets:
# - PASTE_GG_API_KEY
# - GITHUB_WEBHOOK_SECRET
